# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Tensor basics

### Setup Steps

In [0]:
#@title Please enter your registration id to start: (e.g. P181900101) { run: "auto", display-mode: "form" }
Id = "P19A06E_test" #@param {type:"string"}


In [0]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "981234567" #@param {type:"string"}


In [0]:
#@title Run this cell to complete the setup for this Notebook

from IPython import get_ipython
ipython = get_ipython()
  
notebook="BLR_M2W7_DEMO_EXP1" #name of the notebook

def setup():
    ipython.magic("sx pip3 install torch")
   
    print ("Setup completed successfully")
    return

def submit_notebook():
    
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "id" : Id, "file_hash" : file_hash, "notebook" : notebook}

      r = requests.post(url, data = data)
      print("Your submission is successful. Ref:", submission_id)
      return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if Additional: return Additional      
    else: raise NameError('')
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
  
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


In [0]:
import torch
import numpy as np

In [0]:
print(torch.__version__)

0.4.1


#**Tensor**

###Initializing a tensor

In [0]:
#Initializing a tensor
a = torch.tensor([2,3])
a.size()

torch.Size([2])

In [0]:
a.type()

'torch.LongTensor'

###creating scalar tensor

In [0]:
a = torch.tensor(2)
print(a)
print(a.size())

tensor(2)
torch.Size([])


###Converting scalar to python number

In [0]:
print(a.item())
print(type(a.item()))

2
<class 'int'>


###Creating a float tensor

In [0]:
a = torch.tensor([2.0,3])
a.type()

'torch.FloatTensor'

###Providing the data type while creating the tensor

In [0]:
a = torch.tensor([2,3],dtype=torch.int32)
a.type()

'torch.IntTensor'

###Just like numpy, creating a tensor by copying another tensor results to pointing to same memory location

In [0]:
a = torch.tensor([2.0,3])
b = a
b[0]=11
print(a)
print(b)

tensor([11.,  3.])
tensor([11.,  3.])


###2D tensor

In [0]:
a = torch.tensor([[1,2],[3,4]])

###Creating and initializing a tensor with random values

In [0]:
a = torch.rand(3,4)
print(a)

tensor([[0.4293, 0.9488, 0.0102, 0.2872],
        [0.8165, 0.5414, 0.7877, 0.1025],
        [0.0260, 0.7830, 0.0784, 0.4393]])


###Creating and initializing a float tensor with zeros

In [0]:
a = torch.zeros((4,5),dtype=torch.float32)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


###Creating an Identity tensor

In [0]:
a = torch.eye(4,4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#** Tensor Operations**

###Addition of two tensor

In [0]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x+y
print(z)

tensor([[1.3512, 1.4978, 1.1791],
        [0.8383, 0.3460, 1.0782],
        [0.3703, 1.5732, 1.1909]])


###Addition of two tensor (alternative)

In [0]:
z = x.add(y)
print(z)

tensor([[1.3512, 1.4978, 1.1791],
        [0.8383, 0.3460, 1.0782],
        [0.3703, 1.5732, 1.1909]])


###Inplace addition of two tensor

In [0]:
print(x)

x.add_(y)

print(x)

tensor([[0.4961, 0.6035, 0.7177],
        [0.5764, 0.0811, 0.9306],
        [0.0829, 0.7958, 0.8708]])
tensor([[1.3512, 1.4978, 1.1791],
        [0.8383, 0.3460, 1.0782],
        [0.3703, 1.5732, 1.1909]])


###Element wise multiplication

In [0]:
print(x*y)

tensor([[1.1554, 1.3395, 0.5439],
        [0.2195, 0.0917, 0.1593],
        [0.1064, 1.2229, 0.3812]])


###Matrix multiplication

In [0]:
z = torch.matmul(x,y[:,0])
print(z)
z.size()

tensor([1.8865, 1.1173, 1.0708])


torch.Size([3])

###Matrix multiplication (another example)
####The last two dimensions of the Tensors should be matrix multiplicable and the rest of the existing dimension should match

In [0]:
x = torch.rand(5,4,6,2,2)
y = torch.rand(6,2,5)
z= torch.matmul(x,y)
print(z.size())

torch.Size([5, 4, 6, 2, 5])


###Reshaping tensors

In [0]:
x = torch.rand(5,6)
print("Size of x :\n",x.size())
print("x:\n",x)
y = x.view(30)
print("Size of y :\n",y.size())
print("y:\n",y)
z = x.view(-1,10)
print("Size of z :\n",z.size())
print("z:\n",z)


Size of x :
 torch.Size([5, 6])
x:
 tensor([[0.9752, 0.3108, 0.9665, 0.1034, 0.8048, 0.8014],
        [0.8474, 0.7759, 0.7422, 0.6948, 0.3904, 0.6827],
        [0.5480, 0.5234, 0.8875, 0.9944, 0.3839, 0.1024],
        [0.0426, 0.0106, 0.0459, 0.9877, 0.8164, 0.7670],
        [0.4122, 0.0511, 0.5591, 0.2899, 0.8871, 0.0919]])
Size of y :
 torch.Size([30])
y:
 tensor([0.9752, 0.3108, 0.9665, 0.1034, 0.8048, 0.8014, 0.8474, 0.7759, 0.7422,
        0.6948, 0.3904, 0.6827, 0.5480, 0.5234, 0.8875, 0.9944, 0.3839, 0.1024,
        0.0426, 0.0106, 0.0459, 0.9877, 0.8164, 0.7670, 0.4122, 0.0511, 0.5591,
        0.2899, 0.8871, 0.0919])
Size of z :
 torch.Size([3, 10])
z:
 tensor([[0.9752, 0.3108, 0.9665, 0.1034, 0.8048, 0.8014, 0.8474, 0.7759, 0.7422,
         0.6948],
        [0.3904, 0.6827, 0.5480, 0.5234, 0.8875, 0.9944, 0.3839, 0.1024, 0.0426,
         0.0106],
        [0.0459, 0.9877, 0.8164, 0.7670, 0.4122, 0.0511, 0.5591, 0.2899, 0.8871,
         0.0919]])


###Generating Numbers in Sequence

In [0]:
x = torch.arange(9)
x = x.view(3,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


###Concatenating two tensors at a given dimension

In [0]:
print(torch.cat((x,x),dim=0))
print(torch.cat((x,x),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


###Reducing the redundant dimension by squeeze operation

In [0]:
x1= torch.rand(1,5)
print("size of x1 before squeezing:\n",x1.size())
x1 = x1.squeeze()
print("size of x1 before squeezing:\n", x1.size())

size of x1 before squeezing:
 torch.Size([1, 5])
size of x1 before squeezing:
 torch.Size([5])


In [0]:
x2 = torch.rand(3,4,1,5)
print("size of x2 before squeezing:\n",x2.size())
x2 = x2.squeeze()
print("size of x2 before squeezing:\n", x2.size())

size of x2 before squeezing:
 torch.Size([3, 4, 1, 5])
size of x2 before squeezing:
 torch.Size([3, 4, 5])


###Extending the dimension by unsqueeze operation

In [0]:
x = torch.rand(3,4,5,6)
x.unsqueeze(dim=4).size()

torch.Size([3, 4, 5, 6, 1])

###Numpy Bridge
####Converting a numpy array to torch tensor

In [0]:
x = np.array([[1.0,2],[3,4]])
y = torch.from_numpy(x)
print(y)
y.type()

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


'torch.DoubleTensor'

####Converting a torch tensor to numpy array

In [0]:
z = y.numpy()
z.dtype

dtype('float64')

**CUDA Tensors**

####Checking the availability of CUDA/GPU

In [0]:
torch.cuda.is_available()

True

In [0]:
#Linux bash command to print the status of nvidia gpu (memory and processes) 
!nvidia-smi

Sat Nov  3 04:26:36 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    32W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

####Defining the device object (cpu/gpu)

In [0]:
device = torch.device("cuda")
x = torch.rand(3,3)
print(x)
x.type()

tensor([[0.7571, 0.2580, 0.1020],
        [0.3152, 0.1254, 0.1683],
        [0.2777, 0.1500, 0.2544]])


'torch.FloatTensor'

In [0]:
x = x.to(device)
x.type()

'torch.cuda.FloatTensor'


###Transferring the tensor to the respective device (here cpu->gpu)
####Transferring the tensor from gpu->cpu


In [0]:
#Transferring the tensor from gpu->cpu
device_cpu = torch.device("cpu")
x = x.to(device_cpu)
x.type()

'torch.FloatTensor'

### Please answer the questions below to complete the experiment:




In [0]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Too Simple, I am wasting time" #@param ["Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging me", "Was Tough, but I did it", "Too Difficult for me"]


In [0]:
#@title If it was very easy, what more you would have liked to have been added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "test" #@param {type:"string"}

In [0]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["Yes", "No"]

In [0]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id =return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful. Ref: 9463
